src/main/java/com/ikleeen/docs_app/controller/DocumentBean.java
package com.ikleeen.docs_app.controller;

import java.io.Serializable;
import java.util.*;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "documentBean")
@SessionScoped
public class DocumentBean implements Serializable{
 
    private static final long serialVersionUID = 1L;
 
    private String name;
    private String comments;
    private List<Field> fields;

    public DocumentBean()
    {
        fields = new ArrayList();

        fields.add(new Field());
    }

    public void setFields(List<Field> newFields)
    {
       this.fields = newFields;
    }

    public List<Field> getFields()
    {
        return this.fields;
    }

    public void onButtonRemoveFieldClick(final Field p_oField)
    {
        fields.remove(p_oField);
    }

    public void onButtonAddFieldClick()
    {
        fields.add(new Field());
    }

   
    public String getName()
    {
        return name;
    }
 
    public void setName(String name)
    {
        this.name = name;
    }
 
        public String getComments()
    {
        return comments;
    }
 
    public void setComments(String comments)
    {
        this.comments = comments;
    }
    

    public String getSendDocument()
    {
        if("".equals(name) || name == null)
        {   return "" ; }
        else{
            return "Message : Welcome " + name + comments;
            }
    }
 
}

src/main/java/com/ikleeen/docs_app/controller/LoginBean.java
package com.ikleeen.docs_app.controller;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;


@ManagedBean(name = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private static final String[] users = {"kleen:qwerty","kate:123456"};
	
	private String username;
	private String password;
	
	private boolean loggedIn;

	@ManagedProperty(value="#{navigationBean}")
	private NavigationBean navigationBean;
	
	public String doLogin() {
		// Get every user from our sample database :)
		for (String user: users) {
			String dbUsername = user.split(":")[0];
			String dbPassword = user.split(":")[1];
			
			// Successful login
			if (dbUsername.equals(username) && dbPassword.equals(password)) {
				loggedIn = true;
				return navigationBean.toWelcome();
			}
		}
		
		// Set login ERROR
		FacesMessage msg = new FacesMessage("Login error!", "ERROR MSG");
        msg.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext.getCurrentInstance().addMessage(null, msg);
		
		// To to login page
		return navigationBean.toLogin();
		
	}
	
	public String doLogout() {
		// Set the paremeter indicating that user is logged in to false
		loggedIn = false;
		
		// Set logout message
		FacesMessage msg = new FacesMessage("Logout success!", "INFO MSG");
		msg.setSeverity(FacesMessage.SEVERITY_INFO);
		FacesContext.getCurrentInstance().addMessage(null, msg);
		
		return navigationBean.toLogin();
	}


	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isLoggedIn() {
		return loggedIn;
	}

	public void setLoggedIn(boolean loggedIn) {
		this.loggedIn = loggedIn;
	}

	public void setNavigationBean(NavigationBean navigationBean) {
		this.navigationBean = navigationBean;
	}
	
}

src/main/java/com/ikleeen/docs_app/controller/NavigationBean.java
package com.ikleeen.docs_app.controller;

import java.io.Serializable;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean(name = "navigationBean")
@SessionScoped
public class NavigationBean implements Serializable {

	private static final long serialVersionUID = 1L;

	public String toLogin() {
		return "/login.xhtml";
	}
	
	public String toInfo() {
		return "/info.xhtml";
	}
	
	public String toWelcome() {
		return "/secured/welcome.xhtml";
	}
	
}

src/main/webapp/info.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"htth://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
        <title>Info page</title>
    </h:head>
    <h:body>
    	<h:form>
    		<h3>Welcome</h3>
    		<br/>
    		<h:outputText value="Some info about app"/>
    		<br/>
    		<h:commandLink action="#{navigationBean.toLogin}" value="Go to login page"/>
    	</h:form>
    </h:body>
</html>

src/main/webapp/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"htth://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"      
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
        <title>Login form</title>
    </h:head>
    <h:body>
    	<h3>Login here</h3>
    	<h:form id="login-form">
    	   <h:outputText value="username:"/>
    	   <h:inputText value="#{loginBean.username}" id="username"/>
    	   <br/>
    	   <h:outputText value="password:"/>
    	   <h:inputSecret value="#{loginBean.password}" id="password"/>
    	   <br/>
    	   <h:commandButton id="button" value="Login" action="#{loginBean.doLogin}"/>
    	   <br/>
    	   <h:commandLink action="#{navigationBean.toInfo}" value="Info page"/>
    	   <br/>
    	   <h:messages />
    	   <br/>
    	</h:form>
    </h:body>
</html>

src/main/webapp/secured/welcome.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"     
      xmlns:h="http://java.sun.com/jsf/html">
 
    <h:head>
        <title>Documents</title>
    </h:head>
    <h:body>
         <h:form id="form" enctype="multipart/form-data">
            <table width="200" border="1">
                <tr>
                    <td valign="top">Create new document</td>
                </tr>
                <tr> <td> 
                    <label>Title </label>
                    <h:inputText id="name" value="#{documentBean.name}"></h:inputText>
                </td></tr> 
                <tr> <td>
                    <label>Comments </label>
                    <h:inputTextarea id="comments" value="#{documentBean.comments}" cols="40" rows="5" />
                </td></tr> 
                <tr><td> 
                    <h:dataTable id="tblFields" value="#{documentBean.fields}" var="field">
                        <h:column>
                            <h:inputFile value="#{field.value}" />
                        </h:column>
                        <h:column>
                            <h:commandButton value="Remove">
                            <f:ajax listener="#{documentBean.onButtonRemoveFieldClick(field)}" render="@form" /> 
                        </h:commandButton>
                        </h:column> 
                    </h:dataTable>
                <h:commandButton value="Add">
                    <f:ajax listener="#{documentBean.onButtonAddFieldClick}" render="tblFields"  /> 
                </h:commandButton>
                </td></tr> 
                <tr><td> 
                    <h:commandButton value="Send Document">
                        <f:ajax execute="name comments"  render="output"/>
                    </h:commandButton>
                </td></tr> 
            </table>
            <h2><h:outputText id="output" value="#{documentBean.sendDocument}" /></h2>
            </h:form>
        
            <h:form>
    		<h:commandLink action="#{loginBean.doLogout}" value="Logout"/>
            </h:form>
    </h:body>
</html>